rails d scaffold Wof::Game
rails d scaffold Wof::GamePlayer
rails d scaffold Wof::GameModerator
rails d scaffold Wof::PuzzleCategory
rails d scaffold Wof::Puzzle
rails d scaffold Wof::CategoryPuzzle
rails d scaffold Wof::PuzzleWord
rails d scaffold Wof::GamePuzzle
rails d scaffold Wof::GameAction
rails d scaffold Wof::GameModeratorAction
