# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdc5e657a6047e561102a1832e5c7a23dd18ee6d15f949ca2fe1434787fb0548148c4b73bb07769fb6def1de8bdbd15d561009f331113735f531b62b87644960

test:
  secret_key_base: 96f3c0c4d299920bb3988348f3def81cf4a8b1ba31f27048d60477659533b88f63ae8efa22a5ddfbf35f344e67c204c95d3a50edd5409ccf507f8e60c079b3dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
